base_url: "https://the-internet.herokuapp.com"
gitea_url: "http://host.docker.internal:3000"
gitea_username: ""
gitea_password: ""
remote_url: "http://localhost:4444/wd/hub"
browser: "chrome"

findata_url: "http://host.docker.internal:8010"
findata_username: "tester"
findata_password: ""
findata_session_token: "findata-demo-session"

suitecrm_url: "http://host.docker.internal:8081"
suitecrm_api_url: "http://localhost:8081/Api"
suitecrm_username: ""
suitecrm_password: ""
suitecrm_client_id: ""
suitecrm_client_secret: ""

mysql_host: "127.0.0.1"
mysql_port: 3306
mysql_user: "eutl"
mysql_password: ""
mysql_database: "eutl_test"
